fn builtin_runtime_subagent_profiles() -> Vec<RuntimeSubagentProfile> {
    vec![
        builtin_runtime_subagent_profile(
            "coder",
            "Coder",
            "Implementation-focused profile",
            PermissionRuleset::PlanOnly,
            BUILD_AGENT_PROMPT,
            &[],
        ),
        builtin_runtime_subagent_profile(
            "reviewer",
            "Reviewer",
            "Review and risk-focused profile",
            PermissionRuleset::Readonly,
            REVIEW_AGENT_PROMPT,
            &[
                "read",
                "glob",
                "grep",
                "ls",
                "code_search",
                "skill",
                "todoread",
            ],
        ),
        builtin_runtime_subagent_profile(
            "planner",
            "Planner",
            "Plan-first profile for large changes",
            PermissionRuleset::PlanOnly,
            PLAN_AGENT_PROMPT,
            &[
                "read",
                "glob",
                "grep",
                "ls",
                "code_search",
                "skill",
                "todoread",
                "todowrite",
                "question",
            ],
        ),
        builtin_runtime_subagent_profile(
            "general",
            "General",
            "General-purpose subagent for complex multi-step tasks",
            PermissionRuleset::PlanOnly,
            BUILD_AGENT_PROMPT,
            &[],
        ),
        builtin_runtime_subagent_profile(
            "explore",
            "Explore",
            "Read-only code exploration subagent",
            PermissionRuleset::Readonly,
            EXPLORE_AGENT_PROMPT,
            &[
                "read",
                "glob",
                "grep",
                "ls",
                "code_search",
                "skill",
                "todoread",
            ],
        ),
        builtin_runtime_subagent_profile(
            "plan",
            "Plan",
            "Planning subagent for architecture and task breakdowns",
            PermissionRuleset::PlanOnly,
            PLAN_AGENT_PROMPT,
            &[
                "read",
                "glob",
                "grep",
                "ls",
                "code_search",
                "skill",
                "todoread",
                "todowrite",
                "question",
            ],
        ),
    ]
}

fn builtin_runtime_subagent_profile(
    id: &str,
    name: &str,
    description: &str,
    permission: PermissionRuleset,
    prompt: &str,
    tools: &[&str],
) -> RuntimeSubagentProfile {
    RuntimeSubagentProfile {
        id: id.to_string(),
        name: name.to_string(),
        description: description.to_string(),
        mode: "subagent".to_string(),
        permission,
        task_permissions: Vec::new(),
        prompt: prompt.trim_start_matches('\u{feff}').to_string(),
        tools: tools.iter().map(|item| (*item).to_string()).collect(),
        provider: None,
        model: None,
        max_steps: None,
        temperature: None,
        top_p: None,
        color: None,
        disabled: false,
        model_options: BTreeMap::new(),
        hidden: false,
        source_path: None,
    }
}
