include!("agent_profiles/types.rs");
include!("agent_profiles/payload.rs");
include!("agent_profiles/loading.rs");
include!("agent_profiles/builtin.rs");
include!("agent_profiles/parse.rs");
include!("agent_profiles/lookup.rs");
include!("agent_profiles/tools.rs");
include!("agent_profiles/governance.rs");
include!("agent_profiles/permissions.rs");
