fn builtin_agent_profiles() -> Vec<RunAgentProfile> {
    vec![
        builtin_agent_profile(
            "build",
            "Build",
            "Primary implementation agent for coding, testing, and general project work.",
            "primary",
            Some("PLAN_ONLY"),
            BUILD_AGENT_PROMPT,
            &[],
        ),
        builtin_agent_profile(
            "general",
            "General",
            "General-purpose subagent for complex multi-step implementation, debugging, and research tasks.",
            "subagent",
            Some("PLAN_ONLY"),
            BUILD_AGENT_PROMPT,
            &[],
        ),
        builtin_agent_profile(
            "explore",
            "Explore",
            "Read-only code exploration subagent for fast search, mapping, and evidence gathering.",
            "subagent",
            Some("READONLY"),
            EXPLORE_AGENT_PROMPT,
            &[
                "read",
                "glob",
                "grep",
                "ls",
                "code_search",
                "skill",
                "todoread",
            ],
        ),
        builtin_agent_profile(
            "plan",
            "Plan",
            "Planning subagent for architecture analysis, implementation strategy, and task breakdowns.",
            "subagent",
            Some("PLAN_ONLY"),
            PLAN_AGENT_PROMPT,
            &[
                "read",
                "glob",
                "grep",
                "ls",
                "code_search",
                "skill",
                "todoread",
                "todowrite",
                "question",
            ],
        ),
    ]
}

fn builtin_agent_profile(
    id: &str,
    name: &str,
    description: &str,
    mode: &str,
    permission: Option<&str>,
    prompt: &str,
    tools: &[&str],
) -> RunAgentProfile {
    RunAgentProfile {
        id: id.to_string(),
        name: name.to_string(),
        description: Some(description.to_string()),
        mode: mode.to_string(),
        model: None,
        provider: None,
        permission: permission.map(str::to_string),
        task_permissions: Vec::new(),
        prompt: Some(prompt.trim_start_matches('\u{feff}').to_string()),
        tools: tools.iter().map(|item| (*item).to_string()).collect(),
        max_steps: None,
        temperature: None,
        top_p: None,
        color: None,
        disabled: false,
        model_options: BTreeMap::new(),
        hidden: false,
        source_path: None,
        loaded: true,
    }
}
